export const ADD_TASK_REQUEST="ADD_TASK_REQUEST"
export const ADD_TASK_SUCESS="ADD_TASK_SUCESS"
export const ADD_TASK_FAILURE="ADD_TASK_FAILURE"


export const GET_TASK_REQUEST="GET_TASK_REQUEST"
export const GET_TASK_SUCESS="GET_TASK_SUCESS"
export const GET_TASK_FAILURE="GET_TASK_FAILURE"

export const UPDATE_TASK_REQUEST="UPDATE_TASK_REQUEST"
export const UPDATE_TASK_SUCESS="UPDATE_TASK_SUCESS"
export const UPDATE_TASK_FAILURE="UPDATE_TASK_FAILURE"

export const DELETE_TASK_REQUEST="DELETE_TASK_REQUEST"
export const DELETE_TASK_SUCESS="DELETE_TASK_SUCESS"
export const DELETE_TASK_FAILURE="DELETE_TASK_FAILURE"

export const SINGLE_TASK_REQUEST="SINGLE_TASK_REQUEST"
export const SINGLE_TASK_SUCESS="SINGLE_TASK_SUCESS"
export const SINGLE_TASK_FAILURE="SINGLE_TASK_FAILUR"