export const ADMIN_SIGNUP_REQUEST="ADMIN_SIGNUP_REQUEST"
export const ADMIN_SIGNUP_SUCESS="ADMIN_SIGNUP_SUCESS"
export const ADMIN_SIGNUP_FAILURE="ADMIN_SIGNUP_FAILURE"

export const ADMIN_LOGIN_REQUEST="ADMIN_LOGIN_REQUEST"
export const ADMIN_LOGIN_SUCESS="ADMIN_LOGIN_SUCESS"
export const ADMIN_LOGIN_FAILURE="ADMIN_LOGIN_FAILURE"

export const EMPLOYEE_SIGNUP_REQUEST="EMPLOYEE_SIGNUP_REQUEST"
export const EMPLOYEE_SIGNUP_SUCESS="EMPLOYEE_SIGNUP_SUCESS"
export const EMPLOYEE_SIGNUP_FAILURE="EMPLOYEE_SIGNUP_FAILURE"

export const EMPLOYEE_LOGIN_REQUEST="EMPLOYEE_LOGIN_REQUEST"
export const EMPLOYEE_LOGIN_SUCESS="EMPLOYEE_LOGIN_SUCESS"
export const EMPLOYEE_LOGIN_FAILURE="EMPLOYEE_LOGIN_FAILURE"

export const EMPLOYEE_ALL_DATA_REQUEST="EMPLOYEE_ALL_DATA_REQUEST"
export const EMPLOYEE_ALL_DATA_SUCESS="EMPLOYEE_ALL_DATA_SUCESS"
export const EMPLOYEE_ALL_DATA_FAILURE="EMPLOYEE_ALL_DATA_FAILURE"